recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeCreateView,
    RecipeDeleteView,
    RecipeUpdateView,
    log_rating,
    RecipeDetailView,
    RecipeListView,
    ShoppingItemListView,
    create_shopping_item,
    delete_shopping_item,
)

urlpatterns = [
    path("", RecipeListView.as_view(), name="recipes_list"),
    path("<int:pk>/", RecipeDetailView.as_view(), name="recipe_detail"),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe_delete"),
    path("new/", RecipeCreateView.as_view(), name="recipe_new"),
    path("<int:pk>/edit/", RecipeUpdateView.as_view(), name="recipe_edit"),
    path("<int:recipe_id>/ratings/", log_rating, name="recipe_rating"),
    path(
        "shopping_items/",
        ShoppingItemListView.as_view(),
        name="shopping_item_list",
    ),
    path(
        "shopping_items/create/",
        create_shopping_item,
        name="shopping_item_create",
    ),
    path(
        "shopping_items/delete/",
        delete_shopping_item,
        name="shopping_item_delete_all",
    ),
]

scrumptious/urls.py
from typing import Reversible
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("meal_plans_list")),
        name="mealplanhome",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagCreateView,
    TagDetailView,
    TagDeleteView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("new/", TagCreateView.as_view(), name="tags_create"),
    path("<int:pk>", TagDetailView.as_view(), name="tags_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tags_delete"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tags_update"),
]

recipes/models.py
from email import charset
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from django.conf import settings
from django.forms import CharField
from psycopg2 import IntegrityError

# from django.forms import CharField

USER_MODEL = settings.AUTH_USER_MODEL


class Recipe(models.Model):
    name = models.CharField(max_length=125)
    author = models.ForeignKey(
        USER_MODEL,
        related_name="recipes",
        on_delete=models.CASCADE,
        null=True,
    )
    description = models.TextField()
    image = models.URLField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    servings = models.PositiveSmallIntegerField(null=True)

    def __str__(self):
        return self.name + " by " + str(self.author)


class Measure(models.Model):
    name = models.CharField(max_length=30, unique=True)
    abbreviation = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name + " " + self.abbreviation


class FoodItem(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    amount = models.FloatField(
        validators=[MinValueValidator(0), MaxValueValidator(20)]
    )
    recipe = models.ForeignKey(
        "Recipe", related_name="ingredients", on_delete=models.CASCADE
    )
    measure = models.ForeignKey(
        "Measure", related_name="measure", on_delete=models.PROTECT
    )
    food_item = models.ForeignKey(
        "FoodItem", related_name="fooditem", on_delete=models.PROTECT
    )

    def __str__(self):
        return (
            str(self.amount)
            + " "
            + str(self.measure)
            + " "
            + str(self.food_item)
        )


class Step(models.Model):
    recipe = models.ForeignKey(
        "Recipe", related_name="steps", on_delete=models.CASCADE
    )
    order = models.PositiveSmallIntegerField()
    directions = models.TextField(max_length=300)
    food_items = models.ManyToManyField("FoodItem", blank=True)

    def __str__(self):
        return str(self.order) + "." + self.directions


class Rating(models.Model):
    value = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(5), MinValueValidator(1)]
    )
    recipe = models.ForeignKey(
        "Recipe", related_name="ratings", on_delete=models.CASCADE
    )


class ShoppingItem(models.Model):
    user = models.ForeignKey(
        USER_MODEL, related_name="shopping_items", on_delete=models.CASCADE
    )
    food_item = models.ForeignKey("FoodItem", on_delete=models.PROTECT)


# Create your models here.

recipes/forms.py
from django import forms

# try:
from recipes.models import Recipe
from recipes.models import Rating


# class RecipeForm(forms.ModelForm):
#     class Meta:
#         model = Recipe
#         fields = [
#             "name",
#             "author",
#             "description",
#             "image",
#         ]


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["value"]


# except Exception:
#     pass

recipes/views.py
from dataclasses import field
from typing import List
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from psycopg2 import IntegrityError
from recipes.forms import RatingForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods

# try:
# from recipes.forms import RecipeForm
from recipes.models import Ingredient, Recipe, ShoppingItem

# except Exception:
#     RecipeForm = None
#     Recipe = None


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipes/new.html"
    fields = ["name", "description", "image", "servings"]
    success_url = reverse_lazy("recipes_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = "recipes/edit.html"
    fields = ["name", "author", "description", "image", "servings"]
    success_url = reverse_lazy("recipes_list")


class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/list.html"
    paginate_by = 2


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()

        foods = []

        for each in self.request.user.shopping_items.all():
            foods.append(each.food_item)

        context["servings"] = self.request.GET.get("servings")

        context["food_in_shopping_list"] = foods
        return context


def log_rating(request, recipe_id):
    try:  # added try and except block line 50 and 58-59
        if request.method == "POST":
            form = RatingForm(request.POST)
            if form.is_valid():
                rating = form.save(commit=False)
                rating.recipe = Recipe.objects.get(pk=recipe_id)
                rating.save()
        return redirect("recipe_detail", pk=recipe_id)
    except Recipe.DoesNotExist:
        return redirect("recipes_list")


class RecipeDeleteView(DeleteView):
    model = Recipe
    template_name = "recipes/delete.html"
    success_url = reverse_lazy("recipes_list")


@require_http_methods(["POST"])
def create_shopping_item(request):
    id_ingredient = request.POST.get("id_ingredient")
    ingredient = Ingredient.objects.get(id=id_ingredient)
    user = request.user

    try:
        ShoppingItem.objects.create(
            food_item=ingredient.food_item,
            user=user,
        )
    except IntegrityError:
        pass

    return redirect("recipe_detail", pk=ingredient.recipe.id)


class ShoppingItemListView(ListView):
    model = ShoppingItem
    template_name = "shopping_items/list.html"

    def get_queryset(self):
        return ShoppingItem.objects.filter(user=self.request.user)


def delete_shopping_item(request):
    ShoppingItem.objects.filter(user=request.user).delete()
    return redirect("shopping_item_list")


# def show_recipes(request):
#     context = {
#         "recipes": Recipe.objects.all() if Recipe else [],
#     }
#     return render(request, "recipes/list.html", context)


# def create_recipe(request):
#     if request.method == "POST" and RecipeForm:
#         form = RecipeForm(request.POST)
#         if form.is_valid():
#             recipe = form.save()
#             return redirect("recipe_detail", pk=recipe.pk)
#     elif RecipeForm:
#         form = RecipeForm()
#     else:
#         form = None
#     context = {
#         "form": form,
#     }
#     return render(request, "recipes/new.html", context)


# def show_recipe(request, pk):
#     context = {
#         "recipe": Recipe.objects.get(pk=pk) if Recipe else None,
#         "rating_form": RatingForm(),
#     }
#     return render(request, "recipes/detail.html", context)


# def change_recipe(request, pk):
#     if Recipe and RecipeForm:
#         instance = Recipe.objects.get(pk=pk)
#         if request.method == "POST":
#             form = RecipeForm(request.POST, instance=instance)
#             if form.is_valid():
#                 form.save()
#                 return redirect("recipe_detail", pk=pk)
#         else:
#             form = RecipeForm(instance=instance)
#     else:
#         form = None
#     context = {
#         "form": form,
#     }
#     return render(request, "recipes/edit.html", context)

recipes/templates/recipes/delete.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main>
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ recipe.name }}"?</p>
    {{ form.as_p }}
    <div class="control">
      <button class="button">Delete</button>
    </div>
  </form>
</main>

{% endblock content %}

recipes/templates/recipes/detail.html
{% extends "base.html" %} {% load static %} {% load markdownify %} <br />
{% load resizer %} {% block content %}
<main class="recipe-detail">
  <div>
    <a href="{% url 'recipe_edit' recipe.id %}">Edit</a>
    <a href="{% url 'recipe_delete' recipe.id %}">Delete</a>
  </div>
  {% if recipe.image %}
  <img src="{{ recipe.image }}" class="pull-right" />
  {% endif %}
  <h1>{{ recipe.name }}</h1>
  <h2>by: {{ recipe.author | default_if_none:"Unknown" }}</h2>
  <p>Created on {{ recipe.created }} | Updated on {{ recipe.updated }}</p>

  {% if recipe.servings %}
  <p>Serves {{ servings|default_if_none:recipe.servings }}</p>
  <form method="GET">
    <input required type="number" name="servings" />
    <button>Resize</button>
  </form>
  {% endif %}

  <form method="post" action="{% url 'recipe_rating' recipe.id %}">
    {% csrf_token %} {{ rating_form.as_p }}
    <button class="button">Rate</button>
  </form>
  <p>Tags: {% for tag in recipe.tags.all %}{{ tag.name }} {% endfor %}</p>
  {{ recipe.description | markdownify }}
  <h2>Ingredients</h2>
  <table>
    <thead>
      <tr>
        <th colspan="2">Amount</th>
        <th>Food item</th>
      </tr>
    </thead>
    <tbody>
      {% for ingredient in recipe.ingredients.all %}
      <tr>
        <td>{{ ingredient|resize_to:servings }}</td>

        <td>{{ ingredient.measure.name }}</td>
        <td>{{ ingredient.food_item.name }}</td>
        <td>
          {% if ingredient.food_item not in food_in_shopping_list %}
          <form method="POST" action="{% url 'shopping_item_create' %}">
            {% csrf_token %}
            <input
              type="hidden"
              name="id_ingredient"
              value="{{ ingredient.id }}"
            />
            <button>+ shopping list</button>
          </form>
          {% else %} in your list {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <h2>Steps</h2>
  <ol>
    {% for step in recipe.steps.all %}
    <li>{{ step.directions }}</li>
    {% endfor %}
  </ol>
</main>
{% endblock content %} {% comment %} Invalid block tag on line 44: 'endblock'.
Did you forget to register or load this tag? {% endcomment %}

recipes/templates/recipes/edit.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}

recipes/templates/recipes/list.html
{% extends 'base.html' %} {% load static %} {% block content %}

<main class="recipe-grid">
  {% for recipe in recipe_list %}
  <div class="recipe-card">
    <h2 class="recipe-card-title">
      <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
    </h2>
    <p class="recipe-card-date">{{ recipe.updated }}</p>
  </div>
  {% endfor %}
</main>
<footer>
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; First</a>
      <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">Next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
      {% endif %}
    </span>
  </div>
</footer>
{% endblock content %}

recipes/templates/recipes/new.html
{% extends 'base.html' %}{% load static %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>

{% endblock content %}