scrumptious/urls.py
from typing import Reversible
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("meal_plans_list")),
        name="mealplanhome",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagCreateView,
    TagDetailView,
    TagDeleteView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("new/", TagCreateView.as_view(), name="tags_create"),
    path("<int:pk>", TagDetailView.as_view(), name="tags_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tags_delete"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tags_update"),
]

tags/models.py
from django.db import models

from django.forms import CharField


class Tag(models.Model):
    name = models.CharField(max_length=20)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="tags")

    def __str__(self):
        return self.name


# Create your models here.

tags/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from recipes.models import Recipe


# try:
from tags.models import Tag

# except Exception:
#     Tag = None


# Create your views here.


class TagCreateView(LoginRequiredMixin, CreateView):
    model = Tag
    template_name = "tags/new.html"
    fields = ["name", "recipes"]
    success_url = reverse_lazy("tags_list")


class TagUpdateView(LoginRequiredMixin, UpdateView):
    model = Tag
    template_name = "tags/edit.html"
    fields = ["name", "recipes"]
    success_url = reverse_lazy("tags_list")


class TagDeleteView(DeleteView):
    model = Tag
    template_name = "tags/delete.html"
    success_url = reverse_lazy("tags_list")


class TagDetailView(DetailView):
    model = Tag
    template_name = "tags/detail.html"


class TagListView(ListView):
    model = Tag
    template_name = "tags/list.html"
    paginate_by = 2


# def show_tags(request):
#     context = {
#         "tags": Tag.objects.all() if Tag else None,
#     }
#     return render(request, "tags/list.html", context)

tags/templates/tags/delete.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main>
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ tag.name }}"?</p>
    {{ form.as_p }}
    <div class="control">
      <button class="button">Delete</button>
    </div>
  </form>
</main>

{% endblock content %}

tags/templates/tags/detail.html
{% extends "base.html" %} {% load static %} {% load markdownify %} <br />
{% block content%}
<main class="tag-detail">
  <div>
    <a href="{% url 'tags_update' tag.pk %}">Edit</a>
    <a href="{% url 'tags_delete' tag.pk %}">Delete</a>
  <h2>Recipes for {{ tag.name }}</h2>

  {% for recipe in tag.recipes.all %}
  <div class="recipe-card">
    <ul class="recipe-card-title">
      <li><a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
      </li>
    </ul>
{% endfor %}
  </div>
</main>

{% endblock content%}

tags/templates/tags/edit.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">UPDATE</button>
    </div>
  </form>
</main>
{% endblock content %}

tags/templates/tags/list.html
{% extends 'base.html' %} {% load static %} {% block content %}

<a href="{% url 'tags_create' %}">create</a>
<main class="recipe-grid">
  {% for tag in tag_list %}
  <div class="recipe-card">
    <h2 class="recipe-card-title">
      <a href="{% url 'tags_detail' tag.pk %}">{{ tag.name }}</a>
    </h2>
    <p class="recipe-card-date">{{ tag.updated }}</p>
  </div>
  {% endfor %}
</main>
{% endblock content %} {% block pagination %}

<footer>
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; First</a>
      <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">Next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
      {% endif %}
    </span>
  </div>
</footer>
{% endblock pagination %}

tags/templates/tags/new.html
{% extends 'base.html' %}{% load static %} {% block content %}

<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>

{% endblock content %}