meal_plans/urls.py
from django.urls import path

from meal_plans.views import (
    MealPlanListView,
    MealPlanCreateView,
    MealPlanDetailView,
    MealPlanUpdateView,
    MealPlanDeleteView,
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="meal_plan_list"),
    path("new/", MealPlanCreateView.as_view(), name="meal_plan_new"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="meal_plan_detail"),
    path("<int:pk>/edit/", MealPlanUpdateView.as_view(), name="meal_plan_edit"),
    path(
        "<int:pk>/delete/",
        MealPlanDeleteView.as_view(),
        name="meal_plan_delete",
    ),
]

scrumptious/urls.py
from typing import Reversible
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("meal_plans_list")),
        name="mealplanhome",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagCreateView,
    TagDetailView,
    TagDeleteView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("new/", TagCreateView.as_view(), name="tags_create"),
    path("<int:pk>", TagDetailView.as_view(), name="tags_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tags_delete"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tags_update"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings


USER_MODEL = settings.AUTH_USER_MODEL


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField()
    owner = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")


# Create your models here.

meal_plans/views.py
from dataclasses import fields
from django.shortcuts import render
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from meal_plans.models import MealPlan
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin


class MealPlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 4

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("meal_plan_list")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plan_detail", pk=plan.id)


# need explanation on how to use form_valid


class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"
    fields = ["name", "date" "list"]


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("meal_plan_list")


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_plan_list")


# Create your views here.

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main>
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ mealplan.name }}"?</p>
    {{ form.as_p }}
    <div class="control">
      <button class="button">Delete</button>
    </div>
  </form>
</main>

{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends "base.html" %} {% load static %} {% load markdownify %} <br />
{% block content %}

<div>
  <a href="{% url 'meal_plan_edit' mealplan.pk %}">Edit</a>
  <a href="{% url 'meal_plan_delete' mealplan.pk %}">Delete</a>
</div>

<main class="tag-detail">
  <h2>Recipes for {{mealplan.name}} on {{mealplan.date}}</h2>
    {% for recipe in mealplan.recipes.all %} 
    <p>
      <a href="{% url 'recipe_detail' recipe.pk %}"><li>{{ recipe.name }}</a></li>
    </p>
  
    {% endfor %}
</main>

{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %} {% load static %} {% block content %}

<a href="{% url 'meal_plan_new' %}">create</a>

<main class="recipe-grid">   
  {% for mealplan in mealplan_list %}
    <div class="recipe-card">
      <h2 class="recipe-card-title">
        <a href="{% url 'meal_plan_detail' mealplan.pk %}">{{ mealplan.name }}</a>
      </h2>
    <p>Served Date: {{ mealplan.date }}</p>
  {% for recipe in mealplan.recipes.all %}
    <p>
      <a href="{% url 'recipe_detail' recipe.pk %}"><li>{{ recipe.name }}</a></li>
    </p>
  {% endfor %}
    </div>

    {% empty %}
    <h2 class="recipe-card-title">There are no recipes yet.</h2>
</div>
  {% endfor %}
  
</main>

<footer>
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; First</a>
      <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">Next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
      {% endif %}
    </span>
  </div>
</footer>
{% endblock content %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}